# Generated by Django 2.2.12 on 2020-05-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200523_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank='categories/default.jpeg', upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='icon',
            field=models.ImageField(blank='tasks/default.jpeg', upload_to='tasks/'),
        ),
    ]
