# Generated by Django 2.2.12 on 2020-05-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20200524_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='startEnd',
            new_name='endDate',
        ),
    ]
